POSTING_DICT_NAME = "postingDict.index"
POSTING_LISTS_NAME = "postingLists.index"
REPLYTO_DICT_NAME = "replyToDict.index"
REPLYTO_LISTS_NAME = "replyToLists.index"
DOCUMENT_MAP_NAME = "documentMap.index"
